### ISSUE TITLE
Bug: Multiplayer Fails To Connect To Server

### ISSUE THREAD

**Issue by VaelophisNyx** [sebastienvercammen/valheim-SebNetCompressionPlugin#1]
Log becomes packed with error spam about losing connection to the server, and the game stays black screened permanently

**Comment by sebastienvercammen** [comment]
Hey @GalacticRuler, can you clarify a few things?

* Are both the client and the server running SubNetCompressionPlugin?
* Are both client and server using BepInEx Valheim Full (ideally via the updater, which makes sure you've got the right DLLs: https://valheim.thunderstore.io/package/1F31A/BepInEx_Valheim_Full_Updater/)
* For your DLL path:
  * On Windows: In `Valheim\doorstop_config.ini`, does it say `dllSearchPathOverride=BepInEx\core_lib`?
  * On Linux: Does your launch script point to `BepInEx/core_lib`?

A lot of this will be automated in the next releases (at least one releasing today), but for now you'll need to check manually.

**Comment by VaelophisNyx** [comment]
Attempting those steps, the game will launch but BepInEx does not launch with it. We all were using that BPX Release as well.

**Comment by sebastienvercammen** [comment]
@GalacticRuler Can you include both client and server logs, and a copy of your `doorstop_config.ini`?

**Comment by sebastienvercammen** [comment]
Stale issue, last message is 13 days ago.

If this issue still persists, even in the latest version that has been published, let me know here and I'll reopen the issue.
